# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_group_id', models.PositiveIntegerField(default=0, verbose_name='优惠券组ID')),
                ('code', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='优惠券码')),
                ('user_id', models.BigIntegerField(default=0, verbose_name='用户ID')),
                ('order_id', models.CharField(blank=True, max_length=200, verbose_name='订单编号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('order_create_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='订单生成时间')),
                ('drawn_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='被领取时间')),
                ('frozen_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='被冻结时间')),
                ('payed_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='被支付时间')),
            ],
        ),
        migrations.CreateModel(
            name='CouponGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=32, verbose_name='slug')),
                ('name', models.CharField(max_length=200, verbose_name='优惠券组名称')),
                ('title', models.CharField(max_length=200, verbose_name='优惠券组标题')),
                ('comment', models.CharField(max_length=200, verbose_name='优惠券组副标题')),
                ('ware_label_id', models.PositiveIntegerField(verbose_name='商品标签ID')),
                ('favor_type', models.PositiveSmallIntegerField(choices=[(0, '满减券')], default=0, verbose_name='优惠类型')),
                ('scope_type', models.PositiveSmallIntegerField(choices=[(0, '平台券'), (1, '店铺券')], default=0, verbose_name='使用范围')),
                ('sub_type', models.PositiveSmallIntegerField(choices=[(0, '白名单商品'), (1, '黑名单商品'), (2, '全部商品')], default=0, verbose_name='子类型')),
                ('scene_type', models.PositiveSmallIntegerField(choices=[(0, '领取型'), (1, '口令型'), (2, '自动发放型'), (3, '批量导出型'), (4, '批量发放型')], default=0, verbose_name='场景类型')),
                ('full', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='购满金额')),
                ('favor', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='免减金额')),
                ('rate', models.FloatField(default=0, verbose_name='打折折扣率')),
                ('argot', models.CharField(blank=True, max_length=200, verbose_name='口令')),
                ('max_count', models.PositiveIntegerField(default=0, verbose_name='计划最大放出数量')),
                ('delta', models.PositiveIntegerField(default=0, verbose_name='分批生成时的增量')),
                ('drawn_count', models.PositiveIntegerField(default=0, verbose_name='已领取的数量')),
                ('payed_count', models.PositiveIntegerField(default=0, verbose_name='已支付的数量')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('can_draw_count', models.PositiveIntegerField(default=1, verbose_name='每人允许领取数量')),
                ('start_draw_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='领用有效期开始时间')),
                ('end_draw_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='领用有效期结束时间')),
                ('is_duration_type', models.BooleanField(default=False, verbose_name='使用有效期指定时长')),
                ('duration_value', models.PositiveIntegerField(default=0, verbose_name='有效期时长(天)')),
                ('start_use_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='使用有效期开始时间')),
                ('end_use_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='使用有效期结束时间')),
                ('verify_status', models.PositiveSmallIntegerField(choices=[(0, '新建'), (1, '待审批'), (2, '已经上线'), (3, '不通过')], default=0, verbose_name='审批状态')),
                ('delta_verify_status', models.PositiveSmallIntegerField(choices=[(0, '新建'), (1, '待审批'), (2, '已经上线'), (3, '不通过')], default=0, verbose_name='增量审批状态')),
                ('applicant', models.CharField(max_length=200, verbose_name='申请人')),
                ('approver', models.CharField(max_length=200, verbose_name='审批人')),
                ('modifier', models.CharField(max_length=200, verbose_name='修改人')),
                ('seller_id', models.BigIntegerField(default=0, verbose_name='卖家id')),
                ('url', models.URLField(blank=True, default=None, help_text='活动链接', max_length=250, null=True, verbose_name='活动链接')),
                ('img', models.URLField(blank=True, default=None, help_text='图片链接', max_length=250, null=True, verbose_name='图片链接')),
                ('img_width', models.PositiveIntegerField(blank=True, default=0, editable=False, verbose_name='图片宽')),
                ('img_height', models.PositiveIntegerField(blank=True, default=0, editable=False, verbose_name='图片高')),
                ('button_text', models.CharField(max_length=200, verbose_name='按钮文字')),
                ('button_jump', models.CharField(blank=True, max_length=200, verbose_name='按钮跳转')),
                ('jump_label', models.CharField(blank=True, max_length=50, verbose_name='跳转类型')),
                ('jump_data', models.CharField(blank=True, max_length=200, verbose_name='跳转数据')),
                ('argot_jump_label', models.CharField(blank=True, max_length=50, verbose_name='跳转类型')),
                ('argot_jump_data', models.CharField(blank=True, max_length=200, verbose_name='跳转数据')),
                ('update_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='更新时间')),
                ('version', models.PositiveIntegerField(default=0, verbose_name='版本号')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='优惠券组适用范围描述')),
            ],
        ),
        migrations.CreateModel(
            name='UserCoupons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True, verbose_name='用户ID')),
                ('coupon_group_id', models.PositiveIntegerField(default=0, verbose_name='优惠券组ID')),
                ('coupon_id', models.PositiveIntegerField(default=0, verbose_name='优惠券ID')),
                ('code', models.CharField(max_length=200, verbose_name='优惠券码')),
                ('create_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='更新时间')),
                ('use_status', models.PositiveSmallIntegerField(choices=[(0, '已领取'), (1, '已冻结'), (2, '已支付'), (3, '已过期')], default=0, verbose_name='使用状态')),
                ('client_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='客户端ID')),
                ('seller_id', models.BigIntegerField(default=0, verbose_name='卖家id')),
                ('channel_id', models.PositiveIntegerField(choices=[(0, '美啦app'), (1, '美啦web'), (2, '美啦admin'), (3, '美啦电商')], default=0, verbose_name='渠道id')),
            ],
        ),
        migrations.CreateModel(
            name='WareLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='商品标签名称')),
                ('scope_type', models.PositiveSmallIntegerField(choices=[(0, '平台内的商品'), (1, '店铺内的商品')], default=0, verbose_name='使用范围')),
                ('sub_type', models.PositiveSmallIntegerField(choices=[(0, '白名单商品'), (1, '黑名单商品'), (2, '全部商品')], default=0, verbose_name='子类型')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_man', models.CharField(max_length=200, verbose_name='创建人')),
            ],
        ),
        migrations.CreateModel(
            name='WareLabelWares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ware_label_id', models.PositiveIntegerField(db_index=True, verbose_name='商品标签ID')),
                ('ware_id', models.BigIntegerField(verbose_name='商品ID')),
                ('ware_slug', models.CharField(max_length=200, verbose_name='商品slug')),
            ],
        ),
    ]
