# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercoupons',
            name='channel_id',
            field=models.PositiveIntegerField(default=0, verbose_name='渠道id'),
        ),
    ]
