# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnsaleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='slug')),
                ('name', models.CharField(max_length=100, verbose_name='促销活动名称')),
                ('title', models.CharField(max_length=100, verbose_name='促销活动文案')),
                ('comment', models.CharField(max_length=100, verbose_name='促销活动备注')),
                ('favor_type', models.PositiveSmallIntegerField(choices=[(0, '满额减'), (1, '满额折'), (2, '满额换'), (3, '满件换'), (4, '满N件优惠'), (5, 'N件任买')], default=0, verbose_name='优惠类型')),
                ('label_type', models.PositiveSmallIntegerField(choices=[(0, '单商品标签'), (1, '多商品标签')], default=0, verbose_name='商品标签类型')),
                ('ware_label_id', models.PositiveIntegerField(verbose_name='商品标签ID')),
                ('involve_count', models.PositiveIntegerField(default=0, verbose_name='参与次数')),
                ('start_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='活动开始时间')),
                ('end_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='活动结束时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='更新时间')),
                ('verify_status', models.PositiveSmallIntegerField(choices=[(0, '新建'), (1, '待审批'), (2, '已经上线'), (3, '不通过')], default=0, verbose_name='审批状态')),
                ('applicant', models.CharField(max_length=20, verbose_name='申请人')),
                ('approver', models.CharField(max_length=20, verbose_name='审批人')),
                ('modifier', models.CharField(max_length=20, verbose_name='修改人')),
                ('jump_label', models.CharField(blank=True, max_length=100, verbose_name='跳转类型')),
                ('jump_data', models.CharField(blank=True, max_length=200, verbose_name='跳转数据')),
            ],
        ),
        migrations.CreateModel(
            name='Present',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_id', models.PositiveIntegerField(db_index=True, verbose_name='阶梯ID')),
                ('sku_id', models.BigIntegerField(verbose_name='商品ID')),
                ('sku_price', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='商品价格')),
                ('sku_count', models.PositiveIntegerField(db_index=True, verbose_name='商品个数')),
                ('sku_slug', models.CharField(max_length=20, verbose_name='商品slug')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onsale_group_id', models.PositiveIntegerField(verbose_name='促销活动ID')),
                ('full_credit', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='购满金额')),
                ('favor_credit', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='免减金额')),
                ('favor_rate', models.FloatField(default=0, verbose_name='打折折扣率')),
                ('full_count', models.PositiveIntegerField(default=0, verbose_name='购满件数')),
                ('full_rate', models.FloatField(default=0, verbose_name='一件的优惠率,用于满N件优惠')),
                ('full_price', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='金额,用于N件任买')),
            ],
        ),
        migrations.CreateModel(
            name='WareLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='商品标签名称')),
                ('label_type', models.PositiveSmallIntegerField(choices=[(0, '单商品标签'), (1, '多商品标签')], default=0, verbose_name='商品标签类型')),
                ('scope_type', models.PositiveSmallIntegerField(choices=[(0, '全平台'), (1, '店铺内')], default=0, verbose_name='使用范围')),
                ('sub_type', models.PositiveSmallIntegerField(choices=[(0, '商品白名单'), (1, '商品黑名单'), (2, '全部商品')], default=0, verbose_name='商品名单子类型')),
                ('seller_id', models.BigIntegerField(verbose_name='卖家ID')),
                ('seller_slug', models.CharField(max_length=20, verbose_name='卖家slug')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_man', models.CharField(max_length=20, verbose_name='创建人')),
            ],
        ),
        migrations.CreateModel(
            name='WareLabelWares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ware_label_id', models.PositiveIntegerField(db_index=True, verbose_name='商品标签ID')),
                ('ware_id', models.BigIntegerField(verbose_name='商品ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='warelabelwares',
            unique_together=set([('ware_label_id', 'ware_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='present',
            unique_together=set([('step_id', 'sku_id')]),
        ),
    ]
