/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "httpCmd_constants.h"

namespace HttpCmd {

const httpCmdConstants g_httpCmd_constants;

httpCmdConstants::httpCmdConstants() {
}

} // namespace

