/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef couponAdmin_CONSTANTS_H
#define couponAdmin_CONSTANTS_H

#include "couponAdmin_types.h"

namespace couponAdmin {

class couponAdminConstants {
 public:
  couponAdminConstants();

};

extern const couponAdminConstants g_couponAdmin_constants;

} // namespace

#endif
