/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef coupon_CONSTANTS_H
#define coupon_CONSTANTS_H

#include "coupon_types.h"

namespace coupon {

class couponConstants {
 public:
  couponConstants();

};

extern const couponConstants g_coupon_constants;

} // namespace

#endif
