/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "echoCmd_constants.h"

namespace EchoCmd {

const echoCmdConstants g_echoCmd_constants;

echoCmdConstants::echoCmdConstants() {
}

} // namespace

