/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef echoCmd_CONSTANTS_H
#define echoCmd_CONSTANTS_H

#include "echoCmd_types.h"

namespace EchoCmd {

class echoCmdConstants {
 public:
  echoCmdConstants();

};

extern const echoCmdConstants g_echoCmd_constants;

} // namespace

#endif
