/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef couponPush_CONSTANTS_H
#define couponPush_CONSTANTS_H

#include "couponPush_types.h"

namespace couponPush {

class couponPushConstants {
 public:
  couponPushConstants();

};

extern const couponPushConstants g_couponPush_constants;

} // namespace

#endif
