/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef onsale_CONSTANTS_H
#define onsale_CONSTANTS_H

#include "onsale_types.h"

namespace onsale {

class onsaleConstants {
 public:
  onsaleConstants();

};

extern const onsaleConstants g_onsale_constants;

} // namespace

#endif
